# Generated by Django 4.1 on 2025-08-01 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0017_pelicula_cajitavertical_pelicula_imagen1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Capitulo',
            fields=[
                ('id_capitulo', models.AutoField(primary_key=True, serialize=False)),
                ('numero', models.IntegerField(verbose_name='Numero')),
                ('temporada', models.IntegerField(verbose_name='Temporada')),
                ('numero_temporada', models.IntegerField(verbose_name='Numero_de_temporada')),
                ('fecha', models.CharField(default='', max_length=10)),
                ('imdb', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('titulo_ingles', models.CharField(max_length=100)),
                ('titulo_espaniol', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('imagen_vertical', models.ImageField(blank=True, null=True, upload_to='libreria/static/img', verbose_name='Imagen_vertical')),
                ('imagen1_horizontal', models.ImageField(blank=True, null=True, upload_to='libreria/static/img', verbose_name='Imagen1_horizontal')),
                ('imagen2_horizontal', models.ImageField(blank=True, null=True, upload_to='libreria/static/img', verbose_name='Imagen2_horizontal')),
                ('visto', models.BooleanField(default=False, null=True, verbose_name='Vista')),
            ],
        ),
        migrations.CreateModel(
            name='Invitado',
            fields=[
                ('id_invitado', models.AutoField(primary_key=True, serialize=False)),
                ('id_capitulo', models.IntegerField(verbose_name='id_capitulo')),
                ('nombreinvitado', models.CharField(max_length=100)),
                ('imageninvitado', models.ImageField(null=True, upload_to='libreria/static/img', verbose_name='ImagenInvitado')),
                ('textoinvitado', models.TextField(blank=True, default='', null=True, verbose_name='TextoInvitado')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id_review', models.AutoField(primary_key=True, serialize=False)),
                ('id_capitulo', models.IntegerField(verbose_name='id_capitulo')),
                ('plot', models.TextField(blank=True, default='', null=True, verbose_name='Plot')),
                ('textoreview', models.TextField(blank=True, default='', null=True, verbose_name='Textoreview')),
            ],
        ),
        migrations.DeleteModel(
            name='Director',
        ),
        migrations.DeleteModel(
            name='Nota',
        ),
        migrations.DeleteModel(
            name='Pelicula',
        ),
        migrations.RenameField(
            model_name='actor',
            old_name='id',
            new_name='id_actor',
        ),
        migrations.RemoveField(
            model_name='actor',
            name='tipo',
        ),
    ]
