# Generated by Django 4.1 on 2025-09-09 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0018_capitulo_invitado_review_delete_director_delete_nota_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombredirector', models.CharField(max_length=100)),
                ('imagendirector', models.ImageField(null=True, upload_to='img/', verbose_name='ImagenDirector')),
                ('textodirector', models.TextField(blank=True, default='', null=True, verbose_name='TextoDirector')),
                ('tipo', models.CharField(blank=True, default='', max_length=40, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Nota',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=100)),
                ('enlace', models.CharField(max_length=200)),
                ('autor', models.CharField(max_length=100)),
                ('textocorto', models.TextField(blank=True, default='', null=True, verbose_name='TextoCorto')),
            ],
        ),
        migrations.CreateModel(
            name='Pelicula',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('nombre_ingles', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('nombre_alternativo', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('anio', models.IntegerField(verbose_name='Año')),
                ('imagen', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='Imagen')),
                ('director', models.CharField(default='', max_length=100)),
                ('actor_1', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('actor_2', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('actor_3', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('actor_4', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('actor_5', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('actor_6', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('pais', models.CharField(blank=True, default='', max_length=40, null=True)),
                ('imdb', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('resenia', models.TextField(blank=True, null=True, verbose_name='Reseña')),
                ('top10', models.BooleanField(default=False, null=True, verbose_name='Top')),
                ('imagenlocal', models.ImageField(blank=True, null=True, upload_to='img/', verbose_name='ImagenLocal')),
                ('genero', models.CharField(blank=True, default='', max_length=40, null=True)),
                ('subgenero1', models.CharField(blank=True, default='', max_length=40, null=True)),
                ('subgenero2', models.CharField(blank=True, default='', max_length=40, null=True)),
                ('subgenero3', models.CharField(blank=True, default='', max_length=40, null=True)),
                ('color', models.BooleanField(default=False, null=True, verbose_name='Color')),
                ('vista', models.BooleanField(default=False, null=True, verbose_name='Vista')),
                ('cajitavertical', models.ImageField(blank=True, null=True, upload_to='img/', verbose_name='CajitaVertical')),
                ('imagen1', models.ImageField(blank=True, null=True, upload_to='img/', verbose_name='Imagen1')),
                ('imagen2', models.ImageField(blank=True, null=True, upload_to='img/', verbose_name='Imagen2')),
            ],
        ),
        migrations.DeleteModel(
            name='Capitulo',
        ),
        migrations.DeleteModel(
            name='Invitado',
        ),
        migrations.DeleteModel(
            name='Review',
        ),
        migrations.RenameField(
            model_name='actor',
            old_name='id_actor',
            new_name='id',
        ),
        migrations.AddField(
            model_name='actor',
            name='tipo',
            field=models.CharField(blank=True, default='', max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='actor',
            name='imagenactor',
            field=models.ImageField(null=True, upload_to='img/', verbose_name='ImagenActor'),
        ),
    ]
